language: node_js

node_js:
    - "0.10"

env:
    global:
        - secure: | # CODECLIMATE_REPO_TOKEN
            Y6DEGfRf+u6RlA3AU4z8/AM/Ya4Kc6KpBMCYJcdpWPMn9rNd+pIruH/dL
            F/la/gTtqcKs9q8+J4Z15CXrsLgClYaoiAnrJded4g7e+3nVpSnI+ctGl
            ikvSmlGz3yM6/YtBIpWW9dGuzITyi5pUqeFUZOqsnFGUvTiGqLEEiDXWM=
        - COVERALLS_SERVICE_NAME=travis-ci
        - secure: | # COVERALLS_REPO_TOKEN
            WLVPJXmqdoA0p1HYS/CmDtA1iB6kmpbdROLi5OZSvyj89XPhIEZoMCdee
            /CjDhVQRIDVC/XO4gVCFEp50T9aemggpx81f4CiTmt9ENsgdev0hf5p+u
            XrFU1TmUWyn7XVsGV/qS7sZvAQz6TtSkdPDlpT8GW6Tflxk1xI2RxvgBE=

before_script:
    - npm install -g grunt-cli
    - npm install -g codeclimate-test-reporter
    - grunt build

script: grunt test --verbose --force

after_script:
    - grunt report --verbose
    - codeclimate < test/lcov.info
